### PR TITLE
attempt to add share story icon

### PR DESCRIPTION
**Pull request by Efreak**
i wasnt sure how to change the icon itself, and share_plus needs to be added to pubspec. hopefully it works? it seems pretty simple.

sharing for comments still needs to be added.

### CODE REVIEW

**Comment by Livinglist** [comment]
Hi, do you prefer sharing an image containing the text (like a partial screenshot of the comment tile) or just the text itself?

**Comment by Efreak** [comment]
I meant the URL to the comment. The comment itself can be shared by setting the text and using the menu.

**Comment by Livinglist** [comment]
@Efreak if you want to share the url to a story, you can tap on the top right button to open that story in browser and use the share functionality in browser I assume?

**Comment by Efreak** [comment]
Also, I just noticed that there always to be tooltip text for at least some icons? If this is the case, it's not working properly. Unless the title/description is something else. Long pressing the open button just causes a slow animation, and opens the WebView after release

Actually, that last part confuses me; even if there's no tooltip, I'd have expected the flutter built-ins would define longpress separately from tap, similar to how I'd expect a click callback not to fire on a right click. [Icon button](https://api.flutter.dev/flutter/material/IconButton-class.html) says it should be a tooltip property, not a description/title property.

**Comment by Livinglist** [comment]
@Efreak yeah I haven't paid much attention to tooltip yet, I thought it was for accessibility? def gonna improve in future release

**Comment by Efreak** [comment]
> @Efreak if you want to share just the url to a story, you can tap on the top right button to open that story in browser and use the share functionality in browser I assume?

You can, but sharing is *usually* implemented separately anyways. Opening a second app just to open a third is a bit odd, though it's a process I use regularly with apps that add text to the shared URL. The OS doesn't offer to open shared text in a browser unless the browser implements a shared URL receiver; similarly even opening a URL, the OS doesn't offer to open it in a text editor. If I want to collect interesting URLs in an app, or send them to people in a text message, I usually look for a share button.

Direct Share on Android these days also allows apps to add multiple targets to the shared sheet; for example, Messenger adds recent contacts and Pushbullet adds devices.

**Comment by Livinglist** [comment]
> > @Efreak if you want to share just the url to a story, you can tap on the top right button to open that story in browser and use the share functionality in browser I assume?
> 
> You can, but sharing is _usually_ implemented separately anyways. Opening a second app just to open a third is a bit odd, though it's a process I use regularly with apps that add text to the shared URL. The OS doesn't offer to open shared text in a browser unless the browser implements a shared URL receiver; similarly even opening a URL, the OS doesn't offer to open it in a text editor. If I want to collect interesting URLs in an app, or send them to people in a text message, I usually look for a share button.
> 
> Direct Share on Android these days also allows apps to add multiple targets to the shared sheet; for example, Messenger adds recent contacts and Pushbullet adds devices.
> 
> Edit: it's 1:30am here, I'm going to ~sleep~ _read a book_ 🙃.

same timezone lol

**Comment by Livinglist** [comment]
i'm gonna work on design for this a little bit. this probably will go in v0.2.18 instead of v0.2.17 which contains some performance improvement.

**Comment by Livinglist** [comment]
@Efreak which URL you wanna share, the url of hacker news post itself or the url posted inside the post?

**Comment by Livinglist** [comment]
I added a button in bottom sheet, you can now share as shown in the video below. Closing this PR now. Thanks!

https://user-images.githubusercontent.com/7277662/174009879-2a5cbb0e-5860-4279-ba0a-8ebc4254d412.MP4

**Pull request closed without merging**
